YT_shorts_setting: false
asset_size: medium
audio_fps: 44100
duration_crossfade: 1
image_per_time: 0.2
max_paragraphs: 4
max_retries: 5
max_stock_image_length: 4
max_stock_video_length: 7
min_count_images: 1
min_count_videos: 1
min_stock_image_length: 3
min_stock_video_length: 5
orientation: landscape
silence_duration: 2
vid_per_time: 0.8
video_fps: 30
video_height: 1080
video_width: 1920
